apiVersion: v1
kind: Application
metadata:
  name: app-kustomize-staging
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/staging
    repoURL: https://github.com/gsl-meriemelouafi/demoApp.git
    targetRevision: HEAD
